### ISSUE TITLE
Hi Team, I have two ranges that are normal:[[0,100]] and error:[[100,105]] and if value is in between 100.01 to 100.99, it is showing normal color i.e blue, but it should be red color. This is because parseInt is using inside _changeFilledGaugeBarState function in px-gauge.html. It should be parseFloat.

### ISSUE THREAD

**Issue by nehak123** [PredixDev/px-gauge#2]
# Submit an Issue

Hi,

## Expected behavior and actual behavior:
I have two ranges that are normal:[[0,100]] and error:[[100,105]] and if value is in between 100.01 to 100.99, it is showing normal color i.e blue, but it should be red color.

## Steps to reproduce the problem:
1. Set only two ranges normal:[[0,100]] and error:[[100,105]].
2. Enter value in between 100.01 to 100.99

## Possible solution: 
1. Here we can use parseFloat instead of parseInt in px-gauge.html

## Code examples help us better understand the issue - follow the appropriate codepen for the component by going to https://predix-ui.com, finding the component in question, and clicking on the pencil icon under the demo.
Once you've created your code example, you can save it under a new url.
Please note that you should NOT use the same methods for production as the ones used in codepen - these methods are not production ready.

**Comment by nonmetalhail** [comment]
Please fill in the provided template with the requisite information. Thanks.

**Comment by randyaskin** [comment]
Fixed in v2.1.0. I thought it was strange that the bar color was based on percentage instead of raw value anyway, so I no longer parseInt OR parseFloat, but just use the actual numeric `value` and range values.
