### ISSUE TITLE
Setting the min to any value other than 0, disables all defined color settings.

### ISSUE THREAD

**Issue by ppeyro** [PredixDev/px-gauge#5]
Color assignments seem to only work when the min value is 0.  If you set it to a negative value or anything other than 0, the color assignments per range break.

## Screenshots:

![screen shot 2017-09-05 at 10 36 09 am](https://user-images.githubusercontent.com/10835611/30074444-6c9131c0-9226-11e7-920d-9e9cbaccc2c3.png)

![screen shot 2017-09-05 at 10 36 03 am](https://user-images.githubusercontent.com/10835611/30074483-8dcfe69c-9226-11e7-9330-8af16c3d3035.png)

**Comment by randyaskin** [comment]
Fixed in v2.1.0 - now any number can be used for min/max/value and the ranges should reflect correctly.
