### ISSUE TITLE
Gauge component doesn't seem to be responsive.

### ISSUE THREAD

**Issue by ppeyro** [PredixDev/px-gauge#6]
We should work on responsiveness behavior of the gauge component.  
It is not responsive currently.

### Screenshot from a Simulated iphone6:

![screen shot 2017-09-05 at 10 49 07 am](https://user-images.githubusercontent.com/10835611/30074976-4a069904-9228-11e7-9add-f76a6ddc0d20.png)

**Comment by katemenkhaus** [comment]
I believe this is a limitation of the demo page. If you load the gauge in a page by itself it does resize.

**Comment by ppeyro** [comment]
Yes, you are absolutely right.
Component by itself seems to work fine in responsive mode.
Closing this out.
