### ISSUE TITLE
Px-gauge does not show color for negative values

### ISSUE THREAD

**Issue by ana1dasilva** [PredixDev/px-gauge#7]
## Expected behavior and actual behavior:
Expected behavior: when setting the "min" value to a negative number (i.e. min="-100") and then the "value" to zero or a negative number (i.e. value="-20"), the gauge needle should point to the value and the gauge color should be displayed.

Actual behavior: when setting the "min" value to a negative number and then the "vale" to zero or a negative number, the gauge color does not show up (even though the gauge needle seems to be pointing in the right place).

## Steps to reproduce the problem:
1) On the px-gauge element, set the "min" value to a negative number (i.e. -100)
2) Set the "value" to zero or a negative number within the min and max range (i.e. -20)
3) The gauge needle will move to the correct location, but the gauge color will not be displayed.

## Environment (_component version number, Browser (including version), operating system, hardware, etc_):
component version number: v2.2.0
Browser: Google Chrome v63.0.3239.132 (64-bit)
OS: macOS Sierra v10.12.6

## Screenshots (_optional, but very helpful_):
![screen shot 2018-01-09 at 4 54 59 pm](https://user-images.githubusercontent.com/16684569/34745318-1eb15f70-f55e-11e7-825c-023693bd8baa.png)

**Comment by randyaskin** [comment]
The color bands are determined by the `error`, `abnormal`, `anomaly` and `normal` ranges. If you set `min` to -100 and `value` to -20, you need to have a range in one of those 4 properties that correspond to that value, e.g. 
```
<px-gauge min="-100" max="100" value="-20" error="[[-100, 0]]" normal="[[0, 100]]">
```
