### ISSUE TITLE
Add min max indicators below arc

### ISSUE THREAD

**Issue by siddhiparkar151992** [PredixDev/px-gauge#8]
![image](https://user-images.githubusercontent.com/9214789/40412945-401574b0-5e92-11e8-8453-3f852cd25936.png)

Hi,
this would be an enhancement to the existing component.
We had a requirement as having min and max numbers shown below arc for gauage.
Although we managed to add it manually we would like to know if this can be done in future or taken as part of component. Please refer attached image.

**Comment by kh-mubashar** [comment]
@siddhiparkar151992  you can add a wrapper to extend the component functionality 
![capture](https://user-images.githubusercontent.com/19286998/47279580-7dd5e200-d5eb-11e8-911d-70df4a8fe8ca.JPG)
