### ISSUE TITLE
px-gauge svg taking up all width and height

### ISSUE THREAD

**Issue by hannav95** [PredixDev/px-gauge#9]
## Expected behavior and actual behavior:
expected: the chart and gauge should fill the `px-gauge` space. 
actual: The chart is taking up the whole width & height of `px-gauge`

## Environment (_component version number, Browser (including version), operating system, hardware, etc_):
px-gauge 2.3.0, Chrome Version 71.0.3578.98, Windows 10

## Screenshots (_optional, but very helpful_):
![image](https://user-images.githubusercontent.com/12763767/50839355-1ac43380-132e-11e9-8fbb-40941f185e88.png)
![image](https://user-images.githubusercontent.com/12763767/50839402-39c2c580-132e-11e9-8915-072e7fe02b16.png)

## Suggestions: 
Either remove the width & height styles for `#chart` (https://github.com/predixdesignsystem/px-gauge/blob/master/sass/px-gauge.scss#L47) or move the `text-wrapper text--center` div to inside the `div#chart`

**Comment by bentwonk** [comment]
I think this is by design, reading the properties (https://www.predix-ui.com/#/elements/vis/px-gauge).

height: numbernotify
Inherited from PxVisBehavior.baseSize
The height of the component; _generally the height of the charting area for most components._

**Comment by hannav95** [comment]
But since the text number is not included in the chart, it can have weird sizing when the gauge is pushed into smaller places.

**Comment by hannav95** [comment]
My request is that the `52` from the screen shots above be included in height of the chart, which can be done through either of my two suggestions in the original issue. Not sure which one is preferred though. 

With the first suggestion, the `:host` still has styling to use `height: 100%` so removing the height and width on the `#chart` should not affect the components ability to be the height of the charting area.

**Comment by bentwonk** [comment]
Thanks you for your feedback hannav95, we want to build a better platform so its appreciated.
My concern is if I make a change to the height behaviour of the gauge it may break other users implementations, let me confirm the current behaviour with the original design team before I modify it. I am also thinking it may be possible to support the current behaviour as default ( so as not to upset existing implementations) and add a switch to support the changes you suggest for new implementations.

**Comment by hannav95** [comment]
Have you gotten a response from the design team?

**Comment by bentwonk** [comment]
Yes, we discussed it yesterday and agreed your suggestion of including the number within the chart div was far more sensible, thank you. The change will be pushed/approved soon.
